cache: bundler

dist: trusty

services:
  - docker

language: ruby

before_install:
  - mv .env.example .env
  - mv .rspec.example .rspec
  - docker-compose build 

env: 
  - RAILS_ENV=test

script:
  - docker-compose run web rails db:test:prepare
  - docker-compose run web rspec
