version: '3'
services:
  db:
    image: postgres:9.6
    ports:
      - 5433:5432
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - 'redis:/data'
  web:
    build: .
    image: bonsai-asset-index:latest
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/bonsai-asset-index
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    stdin_open: true
    tty: true
  sidekiq:
    image: bonsai-asset-index:latest
    command: bundle exec sidekiq -C config/sidekiq.yml -q default -q mailers
    depends_on:
      - db
      - redis
      - web
    volumes:
      - .:/bonsai-asset-index
    env_file:
      - .env
volumes:
  postgres:
  redis:
  
  